---
Name: config
---
Director:
  rules:
    'cache-include//$Action': 'Heyday\CacheInclude\SilverStripe\Controller'
    
Heyday\CacheInclude\SilverStripe\Controller:
  allowed_actions:
    - clearAll
    - clearTemplate

Injector:
  SSTemplateParser:
    properties:
      closedBlocks:
        cache: "Heyday\CacheInclude\SilverStripe\Extension::cacheTemplate"

  CacheInclude:
    class: Heyday\CacheInclude\CacheInclude
    constructor:
      0: '%$DoctrineCache'
      1: '%$CacheIncludeConfig'

  CacheIncludeConfig:
    class: Heyday\CacheInclude\Configs\ArrayConfig

  CacheIncludeViewableDataProcessor:
    class: Heyday\CacheInclude\Processors\ViewableDataProcessor
    
  CacheIncludeKeyCreator:
    class: Heyday\CacheInclude\KeyCreator\ControllerBased

  DoctrineCache:
      class: Doctrine\Common\Cache\FilesystemCache
      constructor:
        0: '../silverstripe-cacheinclude/cache'
        1: '.cache'

  CacheIncludeController:
    class: Heyday\CacheInclude\SilverStripe\Controller
    constructor:
      0: '%$CacheInclude'

  Heyday\CacheInclude\SilverStripe\Controller:
    class: Heyday\CacheInclude\SilverStripe\Controller
    constructor:
      0: '%$CacheInclude'

  Heyday\CacheInclude\SilverStripe\Extension:
    class: Heyday\CacheInclude\SilverStripe\Extension
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeViewableDataProcessor'
  
  Heyday\CacheInclude\SilverStripe\Extension:
    class: Heyday\CacheInclude\SilverStripe\Extension
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeViewableDataProcessor'

  RequestCache:
    class: Heyday\CacheInclude\RequestCache
    constructor:
      0: '%$CacheInclude'
      1: Global

---
Only:
  CACHEINCLUDE_FORCE_EXPIRE: true
Except:
  environment: live
---
Injector:
  CacheInclude:
    class: Heyday\CacheInclude\CacheInclude
    constructor:
      0: '%$DoctrineCache'
      1: '%$CacheIncludeConfig'
      2: true
