---
Name: config
---
Director:
  rules:
    'cache-include//$Action': 'CacheIncludeController'

Injector:
  CacheInclude:
    class: Heyday\CacheInclude\CacheInclude
    constructor:
      0: '%$CacheCache'
      1: '%$CacheIncludeConfig'
  CacheIncludeConfig:
    class: Heyday\CacheInclude\Configs\ArrayConfig
    constructor:
      0: []
  CacheIncludeViewableDataProcessor:
    class: Heyday\CacheInclude\Processors\ViewableDataProcessor
  Stash:
    class: Stash\Pool
    constructor:
      0: '%$StashDriver'
  StashDriver:
    class: Stash\Driver\FileSystem
    constructor:
      0:
        path: '../silverstripe-cacheinclude/cache'
  CacheIncludeExtension:
    class: CacheIncludeExtension
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeViewableDataProcessor'
  CacheIncludeController:
    class: CacheIncludeController
    constructor:
      0: '%$CacheInclude'
  RequestCache:
    class: Heyday\CacheInclude\RequestCache
    constructor:
      0: '%$CacheInclude'
      1: Global


---
Only:
  CACHEINCLUDE_FORCE_EXPIRE: true
Except:
  environment: live
---
Injector:
  CacheInclude:
    class: Heyday\CacheInclude\CacheInclude
    constructor:
      0: '%$CacheCache'
      1: '%$CacheIncludeConfig'
      2: true
