---
Name: config
---
Director:
  rules:
    'cache-include//$Action': 'Heyday\CacheInclude\SilverStripe\Controller'

Heyday\CacheInclude\SilverStripe\Controller:
  allowed_actions:
    - clearAll
    - clearTemplate

Injector:
  ManyManyList:
    class: Heyday\CacheInclude\SilverStripe\ManyManyList
    
  SSTemplateParser:
    properties:
      closedBlocks:
        cache: "Heyday\CacheInclude\SilverStripe\TemplateParserBlockProvider::cacheTemplate"
      openBlocks:
        cache_include: "Heyday\CacheInclude\SilverStripe\TemplateParserBlockProvider::cacheIncludeTemplate"

  CacheInclude:
    class: Heyday\CacheInclude\CacheInclude
    constructor:
      0: '%$DoctrineCache'
      1: '%$CacheIncludeConfig'

  CacheIncludeExpressionLanguageParserCache:
    class: Heyday\CacheInclude\ExpressionLanguageParserCache
    constructor:
      0: '%$DoctrineCache'

  CacheIncludeExpressionLanguage:
    class: Heyday\CacheInclude\ExpressionLanguage
    constructor:
      0: '%$CacheIncludeExpressionLanguageParserCache'

  CacheIncludeConfig:
    class: Heyday\CacheInclude\Configs\ArrayConfig

  CacheIncludeViewableDataProcessor:
    class: Heyday\CacheInclude\Processors\ViewableDataProcessor

  CacheIncludeKeyCreator:
    class: Heyday\CacheInclude\KeyCreators\ControllerBased

  DoctrineCache:
      class: Doctrine\Common\Cache\FilesystemCache
      constructor:
        0: '../silverstripe-cacheinclude/cache'
        1: '.cache'

  CacheIncludeController:
    class: Heyday\CacheInclude\SilverStripe\Controller
    constructor:
      0: '%$CacheInclude'

  Heyday\CacheInclude\SilverStripe\Controller:
    class: Heyday\CacheInclude\SilverStripe\Controller
    constructor:
      0: '%$CacheInclude'

  Heyday\CacheInclude\SilverStripe\InvalidationExtension:
    class: Heyday\CacheInclude\SilverStripe\InvalidationExtension
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeExpressionLanguage'

  RequestCache:
    class: Heyday\CacheInclude\RequestCache
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeExpressionLanguage'
      2: Global
    properties:
      Tokens:
        - '%$SecurityToken'

      SaveExcludeRules:
        - 'request.getUrl() matches "/^\\/admin|dev/"'

      SaveIncludeRules:
        - "request.httpMethod() == 'GET'"
        - "response.getStatusCode() == 200"

      FetchExcludeRules:
        - 'request.getUrl() matches "/^\\/admin|dev/"'

      FetchIncludeRules:
        - "request.httpMethod() == 'GET'"

---
Only:
  CACHEINCLUDE_FORCE_EXPIRE: true
Except:
  environment: live
---
Injector:
  CacheInclude:
    class: Heyday\CacheInclude\CacheInclude
    constructor:
      0: '%$DoctrineCache'
      1: '%$CacheIncludeConfig'
      2: true
